env:
# N8N configuration
- name: N8N_PORT
  value: '8000'
- name: N8N_HOST
  value: '0.0.0.0'
- name: N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE
  value: 'true'
- name: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
  value: 'false'
- name: WEBHOOK_URL
  value: https://dapps.loca.lt

# Database configuration
- name: DB_TYPE
  value: postgresdb
- name: DB_POSTGRESDB_DATABASE
  value: test_db
- name: DB_POSTGRESDB_SCHEMA
  value: n8n
- name: DB_POSTGRESDB_HOST
  value: instance-f013e711-a496-49c8-a639-ddb8388cff75.database.staging.cloud.databricks.com
- name: DB_POSTGRESDB_PORT
  value: 5432

# Database credentials
- name: DB_POSTGRESDB_USER
  valueFrom: postgres-user
- name: DB_POSTGRESDB_PASSWORD
  valueFrom: postgres-password